import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import "./main.css";
import AppLayout from "./components/Layout";
import EntrancePage from "./pages/Entrance";
import WingPage from "./pages/Wing";
import RoomPage from "./pages/Room";
import DiaryPage from "./pages/Diary";
import TunnelsPage from "./pages/Tunnels";
import ContactsPage from "./pages/Contacts";
import SkillsPage from "./pages/Skills";
createRoot(document.getElementById("root")!).render(<StrictMode><BrowserRouter><Routes><Route element={<AppLayout/>}><Route path="/" element={<EntrancePage/>}/><Route path="/wing/:slug" element={<WingPage/>}/><Route path="/wing/:slug/room/:room" element={<RoomPage/>}/><Route path="/wing/:slug/diary" element={<DiaryPage/>}/><Route path="/tunnels" element={<TunnelsPage/>}/><Route path="/contacts" element={<ContactsPage/>}/><Route path="/skills" element={<SkillsPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes></BrowserRouter></StrictMode>);
